// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9tFHOzKzveyUv76ABhzbxFO96q28cTaU',
    appId: '1:840270607951:web:74217c28fe425a3e8bdc3a',
    messagingSenderId: '840270607951',
    projectId: 'papergraph-cb9c3',
    authDomain: 'papergraph-cb9c3.firebaseapp.com',
    storageBucket: 'papergraph-cb9c3.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADezxsN8OJqzOD98K-tDni8nHfcrdwn-4',
    appId: '1:840270607951:ios:10d2dbe86f6562498bdc3a',
    messagingSenderId: '840270607951',
    projectId: 'papergraph-cb9c3',
    storageBucket: 'papergraph-cb9c3.firebasestorage.app',
    iosBundleId: 'com.papergraph.paperGraph',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9tFHOzKzveyUv76ABhzbxFO96q28cTaU',
    appId: '1:840270607951:web:f3f6cb4cda1f413b8bdc3a',
    messagingSenderId: '840270607951',
    projectId: 'papergraph-cb9c3',
    authDomain: 'papergraph-cb9c3.firebaseapp.com',
    storageBucket: 'papergraph-cb9c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADezxsN8OJqzOD98K-tDni8nHfcrdwn-4',
    appId: '1:840270607951:ios:10d2dbe86f6562498bdc3a',
    messagingSenderId: '840270607951',
    projectId: 'papergraph-cb9c3',
    storageBucket: 'papergraph-cb9c3.firebasestorage.app',
    iosBundleId: 'com.papergraph.paperGraph',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh7hOTFFmWeuw4hOOz7OfQcFmtPGdcSPw',
    appId: '1:840270607951:android:4b416bd12907634f8bdc3a',
    messagingSenderId: '840270607951',
    projectId: 'papergraph-cb9c3',
    storageBucket: 'papergraph-cb9c3.firebasestorage.app',
  );
}
